/* ============================================================
   FREEPICKS · DATA
   All editable copy & seed content lives here.
   Mod actions in the live site override these defaults.
   ============================================================ */

window.FREEPICKS_DATA = {
  /* ---------- BRAND ---------- */
  brand: {
    name: "FREEPICKS",
    tagline: "BET FREE. WIN BOUNTIES.",
    sub: "WORLD CUP 2026 × PUMP.FUN",
    disclaimer:
      "FREE TO PLAY · NO MONEY IN · BOUNTIES PAID OUT VIA PUMP.FUN · 18+ FOR ENTERTAINMENT",
  },

  /* ---------- LINKS ---------- */
  links: {
    x: "https://x.com/",
    pumpfun: "https://pump.fun/",
    coin: "https://pump.fun/", // FREEPICKS token page
    bountyDocs: "https://pump.fun/",
    telegram: "",
  },

  /* ---------- BOUNTY INFO ---------- */
  bounty: {
    headline: "HOW THE BOUNTY WORKS",
    body: [
      "FREEPICKS runs entirely on pump.fun's BOUNTY system.",
      "Every match has its own bounty pool — usually around $1,000, funded by $FREEPICKS creator fees.",
      "To win, you have to nail 5 predictions on a single match. All 5 must be correct.",
      "After full-time, the final stats are posted on X. Every player who got all 5 right splits the pump.fun bounty.",
    ],
    steps: [
      { n: "01", t: "PICK A MATCH",       d: "Pick any open World Cup fixture." },
      { n: "02", t: "ANSWER 5 PREDICTIONS", d: "Winner · Total Goals · First Goal · BTTS · Scorer." },
      { n: "03", t: "WAIT FOR FULL TIME", d: "We post the official result on X after the final whistle." },
      { n: "04", t: "WINNERS GET TAGGED", d: "All 5 right? You get tagged on pump.fun for payout." },
    ],
  },

  /* ---------- MATCHES (SEED) ----------
     Real-ish World Cup 2026 fixtures, ordered by kickoff.
     odds: home / draw / away (American format).
     status: "open" | "live" | "final" | "hidden" */
  matches: [
    {
      id: "wc26-m1",
      group: "GROUP A",
      home: { code: "MEX", name: "MEXICO",        flag: "mx" },
      away: { code: "CAN", name: "CANADA",        flag: "ca" },
      venue: "ESTADIO AZTECA",
      city: "MEXICO CITY",
      kickoff: "2026-06-11T20:00:00Z",
      prizeUsd: 1000,
      bountyPool: 2,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      status: "open",
      players: [
        "RAUL JIMENEZ", "HIRVING LOZANO", "SANTI GIMENEZ", "EDSON ALVAREZ",
        "JONATHAN DAVID", "ALPHONSO DAVIES", "CYLE LARIN", "TAJON BUCHANAN",
      ],
    },
    {
      id: "wc26-m2",
      group: "GROUP D",
      home: { code: "USA", name: "UNITED STATES", flag: "us" },
      away: { code: "PAR", name: "PARAGUAY",      flag: "py" },
      venue: "SOFI STADIUM",
      city: "LOS ANGELES",
      kickoff: "2026-06-12T18:00:00Z",
      prizeUsd: 1000,
      bountyPool: 3,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      status: "open",
      players: [
        "CHRISTIAN PULISIC", "FOLARIN BALOGUN", "TIM WEAH", "GIO REYNA",
        "ANTONIO SANABRIA", "MIGUEL ALMIRON", "JULIO ENCISO",
      ],
    },
    {
      id: "wc26-m3",
      group: "GROUP C",
      home: { code: "ARG", name: "ARGENTINA",     flag: "ar" },
      away: { code: "KSA", name: "SAUDI ARABIA",  flag: "sa" },
      venue: "BMO FIELD",
      city: "TORONTO",
      kickoff: "2026-06-12T21:00:00Z",
      prizeUsd: 1500,
      bountyPool: 2.5,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      status: "open",
      players: [
        "LIONEL MESSI", "LAUTARO MARTINEZ", "JULIAN ALVAREZ", "ANGEL DI MARIA",
        "SALEM AL-DAWSARI", "SALEH AL-SHEHRI", "FIRAS AL-BURAIKAN",
      ],
    },
    {
      id: "wc26-m4",
      group: "GROUP F",
      home: { code: "BRA", name: "BRAZIL",        flag: "br" },
      away: { code: "MAR", name: "MOROCCO",       flag: "ma" },
      venue: "METLIFE STADIUM",
      city: "NEW JERSEY",
      kickoff: "2026-06-13T17:00:00Z",
      prizeUsd: 1500,
      bountyPool: 4,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      status: "open",
      players: [
        "VINICIUS JR", "RODRYGO", "ENDRICK", "RAPHINHA", "NEYMAR",
        "HAKIM ZIYECH", "ACHRAF HAKIMI", "EN-NESYRI",
      ],
    },
    {
      id: "wc26-m5",
      group: "GROUP H",
      home: { code: "FRA", name: "FRANCE",        flag: "fr" },
      away: { code: "SEN", name: "SENEGAL",       flag: "sn" },
      venue: "BC PLACE",
      city: "VANCOUVER",
      kickoff: "2026-06-13T20:00:00Z",
      prizeUsd: 1000,
      bountyPool: 3.5,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      status: "open",
      players: [
        "KYLIAN MBAPPE", "ANTOINE GRIEZMANN", "MARCUS THURAM", "OUSMANE DEMBELE",
        "SADIO MANE", "ILIMAN NDIAYE", "NICOLAS JACKSON",
      ],
    },
    {
      id: "wc26-m6",
      group: "GROUP B",
      home: { code: "ENG", name: "ENGLAND",       flag: "gb-eng" },
      away: { code: "ECU", name: "ECUADOR",       flag: "ec" },
      venue: "GILLETTE STADIUM",
      city: "FOXBOROUGH",
      kickoff: "2026-06-14T17:00:00Z",
      prizeUsd: 1000,
      bountyPool: 3,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      status: "open",
      players: [
        "HARRY KANE", "BUKAYO SAKA", "PHIL FODEN", "JUDE BELLINGHAM", "COLE PALMER",
        "ENNER VALENCIA", "MOISES CAICEDO", "KENDRY PAEZ",
      ],
    },
    {
      id: "wc26-m7",
      group: "GROUP E",
      home: { code: "GER", name: "GERMANY",       flag: "de" },
      away: { code: "JPN", name: "JAPAN",         flag: "jp" },
      venue: "MERCEDES-BENZ STADIUM",
      city: "ATLANTA",
      kickoff: "2026-06-14T21:00:00Z",
      prizeUsd: 1250,
      bountyPool: 4,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      status: "open",
      players: [
        "KAI HAVERTZ", "FLORIAN WIRTZ", "JAMAL MUSIALA", "NICLAS FULLKRUG",
        "TAKEFUSA KUBO", "KAORU MITOMA", "DAICHI KAMADA",
      ],
    },
    {
      id: "wc26-m8",
      group: "GROUP G",
      home: { code: "POR", name: "PORTUGAL",      flag: "pt" },
      away: { code: "URU", name: "URUGUAY",       flag: "uy" },
      venue: "HARD ROCK STADIUM",
      city: "MIAMI",
      kickoff: "2026-06-15T19:00:00Z",
      prizeUsd: 2000,
      bountyPool: 5,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      status: "open",
      players: [
        "CRISTIANO RONALDO", "BRUNO FERNANDES", "JOAO FELIX", "RAFAEL LEAO",
        "DARWIN NUNEZ", "FEDERICO VALVERDE", "MAXI ARAUJO",
      ],
    },
  ],

  /* ---------- PARLAYS (SEED) ---------- */
  // status: "open" | "locked" | "won" | "lost"
  // bountyToken: "SOL" | "FREEPICKS" | "USDC" | etc.
  parlays: [
    {
      id: "wc26-001",
      title: "OPENING SHOCK",
      subtitle: "MATCHDAY 1 · GROUP A/B/C",
      legs: 3,
      difficulty: "EASY",
      bountyPool: 5,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      kickoff: "2026-06-11T20:00:00Z",
      status: "open",
      legsList: [
        { match: "MEX vs CAN", pick: "MEXICO TO WIN",       odds: "-140" },
        { match: "USA vs PAR", pick: "OVER 2.5 GOALS",      odds: "-110" },
        { match: "ARG vs KSA", pick: "ARG -1.5 HANDICAP",   odds: "+105" },
      ],
      entrants: 0,
      winners: 0,
      accent: "pink",
    },
    {
      id: "wc26-002",
      title: "GOAL FRENZY",
      subtitle: "MATCHDAY 2 · ALL OVERS",
      legs: 4,
      difficulty: "MEDIUM",
      bountyPool: 10,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      kickoff: "2026-06-12T18:00:00Z",
      status: "open",
      legsList: [
        { match: "GER vs JPN", pick: "OVER 2.5 GOALS", odds: "-130" },
        { match: "FRA vs SEN", pick: "OVER 2.5 GOALS", odds: "-115" },
        { match: "ENG vs ECU", pick: "OVER 1.5 GOALS", odds: "-260" },
        { match: "BRA vs MAR", pick: "BTTS YES",       odds: "-105" },
      ],
      entrants: 0,
      winners: 0,
      accent: "green",
    },
    {
      id: "wc26-003",
      title: "UNDERDOG ROYALE",
      subtitle: "DOG WALK · 3 LEGS",
      legs: 3,
      difficulty: "HARD",
      bountyPool: 25,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      kickoff: "2026-06-13T17:00:00Z",
      status: "open",
      legsList: [
        { match: "POR vs URU", pick: "URUGUAY DRAW NO BET", odds: "+220" },
        { match: "BEL vs CRO", pick: "CROATIA TO WIN",      odds: "+260" },
        { match: "NED vs SEN", pick: "DRAW",                odds: "+240" },
      ],
      entrants: 0,
      winners: 0,
      accent: "yellow",
    },
    {
      id: "wc26-004",
      title: "USA BLITZ",
      subtitle: "HOSTS SPECIAL · 3 LEGS",
      legs: 3,
      difficulty: "MEDIUM",
      bountyPool: 7.5,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      kickoff: "2026-06-14T22:00:00Z",
      status: "open",
      legsList: [
        { match: "USA vs PAR", pick: "PULISIC TO SCORE",   odds: "+180" },
        { match: "USA vs PAR", pick: "USA TO WIN",         odds: "-120" },
        { match: "USA vs PAR", pick: "OVER 2.5 GOALS",     odds: "-110" },
      ],
      entrants: 0,
      winners: 0,
      accent: "cyan",
    },
    {
      id: "wc26-005",
      title: "EUROPE SWEEP",
      subtitle: "5 LEG MONSTER",
      legs: 5,
      difficulty: "DEGEN",
      bountyPool: 100,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      kickoff: "2026-06-15T19:00:00Z",
      status: "open",
      legsList: [
        { match: "FRA vs SEN", pick: "FRANCE TO WIN",  odds: "-180" },
        { match: "ENG vs ECU", pick: "ENGLAND TO WIN", odds: "-220" },
        { match: "GER vs JPN", pick: "GERMANY TO WIN", odds: "-160" },
        { match: "ESP vs CRC", pick: "SPAIN -2.5",     odds: "+130" },
        { match: "POR vs URU", pick: "PORTUGAL TO WIN",odds: "-115" },
      ],
      entrants: 0,
      winners: 0,
      accent: "pink",
    },
    {
      id: "wc26-006",
      title: "SOUTH AMERICAN STORM",
      subtitle: "CONMEBOL CARNAGE",
      legs: 3,
      difficulty: "MEDIUM",
      bountyPool: 8,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      kickoff: "2026-06-16T21:00:00Z",
      status: "open",
      legsList: [
        { match: "ARG vs KSA", pick: "MESSI TO SCORE",    odds: "+115" },
        { match: "BRA vs MAR", pick: "VINI JR ANYTIME",   odds: "+105" },
        { match: "URU vs POR", pick: "OVER 2.5 GOALS",    odds: "-105" },
      ],
      entrants: 0,
      winners: 0,
      accent: "green",
    },
    {
      id: "wc26-007",
      title: "AFRICAN UPRISING",
      subtitle: "CAF SHOCKER · 3 LEGS",
      legs: 3,
      difficulty: "HARD",
      bountyPool: 15,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      kickoff: "2026-06-17T16:00:00Z",
      status: "open",
      legsList: [
        { match: "MAR vs CRO", pick: "MOROCCO DRAW NO BET", odds: "+170" },
        { match: "SEN vs NED", pick: "SENEGAL TO SCORE",    odds: "-130" },
        { match: "GHA vs KOR", pick: "GHANA OR DRAW",       odds: "+140" },
      ],
      entrants: 0,
      winners: 0,
      accent: "yellow",
    },
    {
      id: "wc26-008",
      title: "FINAL BOSS",
      subtitle: "ULTIMATE · 7 LEGS",
      legs: 7,
      difficulty: "DEGEN",
      bountyPool: 500,
      bountyToken: "SOL",
      pumpfunUrl: "https://pump.fun/",
      kickoff: "2026-06-18T20:00:00Z",
      status: "open",
      legsList: [
        { match: "ARG vs MEX", pick: "ARG TO WIN",       odds: "-150" },
        { match: "BRA vs SUI", pick: "BRA TO WIN",       odds: "-180" },
        { match: "FRA vs DEN", pick: "FRA TO WIN",       odds: "-130" },
        { match: "ENG vs USA", pick: "OVER 2.5 GOALS",   odds: "-110" },
        { match: "GER vs ESP", pick: "BTTS YES",         odds: "-140" },
        { match: "POR vs GHA", pick: "POR -1.5",         odds: "+115" },
        { match: "NED vs ECU", pick: "NED TO WIN",       odds: "-160" },
      ],
      entrants: 0,
      winners: 0,
      accent: "pink",
    },
  ],

  /* ---------- LEADERBOARD (SEED) ---------- */
  leaderboard: [
    { rank: 1, handle: "@solbagger",     hits: 14, bounty: 87.5,  badge: "GOAT"   },
    { rank: 2, handle: "@degenrico",     hits: 12, bounty: 64.2,  badge: "PRO"    },
    { rank: 3, handle: "@parlaypapi",    hits: 11, bounty: 55.0,  badge: "PRO"    },
    { rank: 4, handle: "@chainpicks",    hits: 9,  bounty: 38.7,  badge: ""       },
    { rank: 5, handle: "@frankocean",    hits: 8,  bounty: 31.0,  badge: ""       },
    { rank: 6, handle: "@cryptocapper",  hits: 7,  bounty: 24.6,  badge: ""       },
    { rank: 7, handle: "@vibegoat",      hits: 6,  bounty: 19.2,  badge: ""       },
    { rank: 8, handle: "@miamiwhale",    hits: 5,  bounty: 14.0,  badge: ""       },
  ],

  /* ---------- POOL TOTALS (cosmetic) ---------- */
  pool: {
    totalSol: 670.5,
    totalEntries: 1284,
    totalWinners: 47,
    coinAddress: "FREEPICKS...soon",
  },
};
